
include ../../include.mk

OUTDIR = ../../bin

KEY_FILE = ../../db4objects.snk

TARGET = exe
ASSEMBLY = $(TOOL)
REFERENCES = -r:$(OUTDIR)/$(CORE) -r:$(OUTDIR)/$(OPTIONAL) -r:$(OUTDIR)/$(INSTR) -r:$(OUTDIR)/$(NQ) -r:$(OUTDIR)/$(CECIL) -r:$(OUTDIR)/$(FLOWANALYSIS) -r:$(OUTDIR)/$(GETOPTIONS)
