/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_db4o_util_io_win32_Win32IoAdapter */

#ifndef _Included_com_db4o_util_io_win32_Win32IoAdapter
#define _Included_com_db4o_util_io_win32_Win32IoAdapter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_db4o_util_io_win32_Win32IoAdapter_COPY_SIZE
#define com_db4o_util_io_win32_Win32IoAdapter_COPY_SIZE 4096L
/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    openFile
 * Signature: (Ljava/lang/String;ZJ)J
 */
JNIEXPORT jlong JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_openFile
  (JNIEnv *, jclass, jstring, jboolean, jlong);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_closeFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    getLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_getLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    read
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    seek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_seek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    sync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_sync
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    write
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_db4o_util_io_win32_Win32IoAdapter
 * Method:    copy
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_com_db4o_util_io_win32_Win32IoAdapter_copy
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
